name: Install Addon Environment
description: Clones windower and common, initializes windower environment

inputs:
  access-token:
    description: 'PAT with repository scope (https://github.com/settings/tokens)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: clone "thexder-ffxi/common"
      uses: $/actions/clone-github-repo
      with:
        owner: thexder-ffxi
        repository: common
        access-token: ${{ inputs.access-token }} # private repo access
        depth: 1
        branch: main
        path: $RUNNER_WORKSPACE

    - name: install windower environment
      uses: $/actions/install-windower-environment
      with:
        access-token: ${{ inputs.access-token }} # private repo access
