name: Release addon
description: Builds, tests and releases an addon

inputs:
  access-token:
    description: 'PAT with repository scope (https://github.com/settings/tokens)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: install lua 5.1
      run: |
        # set -x
        sudo apt-get update
        sudo apt-get install lua5.1
      shell: bash

    - name: checkout "${{github.repository}}"
      uses: actions/checkout@v4
        
    - name: install addon environment
      uses: $/actions/install-addon-environment
      with:
        access-token: ${{ inputs.access-token }} # private repo access

    - name: test addon
      uses: $/actions/test-addon
      with:
        args: "--config-file=bstd.lua"

    - name: release addon artefact
      uses: $/actions/release-addon
