name: Build addon
description: Builds and uploads an addon

inputs:
  access-token:
    description: 'PAT with repository scope (https://github.com/settings/tokens)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: install lua 5.1
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install lua5.1
      shell: bash
        
    - name: base directory
      run: |
        echo "${{ github.ref }}|${{ github.event.ref }}"
        git --version
        lua -v
        env
        pwd
      shell: bash

    - name: checkout "${{github.repository}}"
      uses: actions/checkout@v4
        
    - name: install addon environment
      uses: thexder-ffxi/github/actions/install-addon-environment@main
      with:
        access-token: ${{ inputs.access-token }} # private repo access

    - name: check directories
      run: |
        pwd
        ls -d */
        cd ..
        pwd
        ls -d */
      shell: bash

    - name: test addon
      uses: thexder-ffxi/github/actions/test-addon@main
      with:
        args: "--config-file=bstd.lua"

    - name: build addon artefact
      uses: thexder-ffxi/github/actions/build-addon@main
